### ISSUE TITLE
Doesn't seem to execute on Ubuntu 18.04

### ISSUE THREAD

**Issue by andrewpwade** [vmware/cloud-init-vmware-guestinfo#6]
Hi,

Sorry if this is the wrong place for support!

cloud-init 18.5-45-g3554ffe8-0ubuntu1~18.04.1

I followed the install instructions. I suspected the DataSource wasn't being run, so I edited `/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMwareGuestInfo.py` to raise an exception in `__init__`. Then I ran

`sudo rm -rf /var/lib/cloud/instances/ /var/lib/cloud/data/upgraded-network && sudo cloud-init -d init`

I get no errors - beginning of the log is at https://gist.github.com/andrewpwade/c4bdad2cce4dd9d35486dbbeadc2d44c

There are only two config files in `/etc/cloud/cloud.cfg.d/` : the one the installer created with `datasource_list: [ "VMwareGuestInfo" ]` and the logging config.

**Comment by andrewpwade** [comment]
OK, after digging through cloud-init's "interesting" usages of "except Exception" it seems to a problem with my cloud-config.yml, as I got it to log "18.5-45-g3554ffe8-0ubuntu1~18.04.1 finished at Thu, 16 May 2019 15:11:01 +0000. Datasource DataSourceVMwareGuestInfo." and it's set the hostname that was in my config.

**Comment by akutz** [comment]
Great! I'm sorry I didn't respond sooner, but I've got a dentist appointment this morning, and I've been trying to wrap up some other stuff before I depart.
